analysis_settings:
  high_freq_cutoff: 0.45
  low_freq_cutoff: 0.361505
  temperature_columns:
  - 4K
  - 30K
  - 100K
  - 300K
  weight_settings:
    background_weight: 0.01
    between_peaks_weight: 0.6
    high_freq_peak_weight: 1.0
    lp_up_peak_weight: 1.0
    model_types:
    - H_form
    - B_form
    peak_distance: 10
    peak_height_threshold: 0.01
    peak_prominence_threshold: 0.05
bayesian_priors:
  gamma_parameters:
    log_gamma_min:
      distribution: Normal
      sigma: 1.0
    log_gamma_other:
      distribution: Normal
      sigma: 1.0
  magnetic_parameters:
    B4:
      distribution: Normal
      sigma: 0.001
    B6:
      distribution: Normal
      sigma: 0.0001
    a_scale:
      distribution: HalfNormal
      sigma: 1.0
    g_factor:
      distribution: Normal
      sigma: 0.1
  noise_parameters:
    sigma:
      distribution: HalfNormal
      sigma: 0.05
  with_prior_info:
    B4:
      distribution: Normal
      sigma: 0.001
    B6:
      distribution: Normal
      sigma: 0.0001
    a_scale:
      distribution: Normal
      sigma: 0.5
    g_factor:
      distribution: Normal
      sigma: 0.1
execution:
  use_gpu: false
file_paths:
  data_file: C:\Users\taich\OneDrive - YNU(ynu.jp)\master\磁性\GGG\Programs\corrected_exp_datasets\Corrected_Transmittance_Temperature.xlsx
  results_parent_dir: analysis_results_2param_gamma
  sheet_name: Corrected Data
mcmc:
  chains: 4
  draws: 4000
  init: jitter+adapt_diag
  max_iterations: 2
  random_seed: 42
  simplified_gamma: false
  target_accept: 0.95
  tune: 2000
physical_parameters:
  B_fixed: 9.0
  N_spin: 1.9386e+28
  d_fixed: 0.0001578
  initial_values:
    B4: 0.0003
    B6: 3.0e-05
    a_scale: 0.69
    eps_bg: 14.2
    g_factor: 1.99
    gamma: 0.11e12
  s: 3.5
